//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class license
    {
        public license()
        {
            this.transportation = new HashSet<transportation>();
        }
    
        public string id { get; set; }
        public int employee_id { get; set; }
        public bool has_bus_license { get; set; }
    
        public virtual ICollection<transportation> transportation { get; set; }
    }
}
