//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class passenger
    {
        public passenger()
        {
            this.transportation_passangers = new HashSet<transportation_passangers>();
        }
    
        public int Id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string pohne { get; set; }
        public string address { get; set; }
        public bool deleted { get; set; }
    
        public virtual ICollection<transportation_passangers> transportation_passangers { get; set; }
    }
}
