//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class transportation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public transportation()
        {
            this.transportation_passangers = new HashSet<transportation_passangers>();
        }
    
        public int Id { get; set; }
        public int employee_id { get; set; }
        public int customer_id { get; set; }
        public double income { get; set; }
        public int vehicle_assign_id { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual employee employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transportation_passangers> transportation_passangers { get; set; }
        public virtual vehicle_assign vehicle_assign { get; set; }
    }
}
